name: Build Oolite and all dependencies

on:
  workflow_dispatch: # add run button in github
jobs:
  run:

    runs-on: windows-2025

    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: |
        echo c: | setup.cmd
