name: Build Oolite

on:
  workflow_dispatch: # add run button in github
jobs:
  run:

    runs-on: windows-2025

    steps:
    - uses: actions/checkout@v4
    - name: Set up MSYS2 (MinGW)
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
    - name: Install
      shell: msys2 {0}
      run: |
        ./install.sh
