name: Release Oolite packages

on:
  release:
    types: [published]   # Trigger only when a new release is published
permissions:
  contents: write
jobs:
  run:
    runs-on: windows-2025

    steps:
    - uses: actions/checkout@v6
    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        
    - name: Install gcc
      shell: msys2 {0}
      env:
        msystem: MINGW64
      run: |
        ./install.sh gcc
    # Upload artifacts to the release
    - name: Upload to GitHub Release
      if: success()
      uses: softprops/action-gh-release@v2
      with:
        files: packages/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Uninstall MINGW64 packages
      shell: msys2 {0}
      run: |
        # Remove all mingw64 packages to avoid mixing
        pacman -Rns --noconfirm $(pacman -Qq | grep '^mingw-w64-x86_64-')

    - name: Install clang
      shell: msys2 {0}
      env:
        msystem: UCRT64
      run: |
        ./install.sh clang
    # Upload artifacts to the release
    - name: Upload to GitHub Release
      if: success()
      uses: softprops/action-gh-release@v2
      with:
        files: packages/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete release and tag on failure
      if: failure()
      run: |
        # Install GitHub CLI
        choco install gh -y

        # Authenticate GitHub CLI
        gh auth login --with-token < $env:GITHUB_TOKEN

        # Delete the release and tag
        gh release delete $env:GITHUB_REF_NAME --cleanup-tag --yes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REF_NAME: ${{ github.event.release.tag_name }}
